spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/newhope?characterEncoding=UTF-8&serverTimezone=Asia/Jakarta
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    initSQL: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
  jpa:
    hibernate:
      jdbc:
        time_zone: Asia/Jakarta
      ddl-auto: validate # 운영시에는 validate 추천
    show-sql: true

  flyway:
    enabled: true
    url: jdbc:mysql://127.0.0.1:3308/newhope?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    baselineOnMigrate: true
    encoding: UTF-8
    out-of-order: true
    table: schema_version
    user: root
    password: 1234